[project]
name = "app"
version = "0.1.0"
description = "AI Native APM backend"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.115.0",
    "mcp[cli]>=2.0.0",
    "pydantic-settings>=2.15.0",
    "python-dotenv>=1.2.3",
]

[project.optional-dependencies]
otel = [
    "opentelemetry-distro>=0.65b0",
    "opentelemetry-exporter-otlp>=1.44.0",
    "opentelemetry-instrumentation-asyncio==0.65b0",
    "opentelemetry-instrumentation-click==0.65b0",
    "opentelemetry-instrumentation-dbapi==0.65b0",
    "opentelemetry-instrumentation-exceptions==0.65b0",
    "opentelemetry-instrumentation-fastapi==0.65b0",
    "opentelemetry-instrumentation-grpc==0.65b0",
    "opentelemetry-instrumentation-httpx==0.65b0",
    "opentelemetry-instrumentation-jinja2==0.65b0",
    "opentelemetry-instrumentation-logging==0.65b0",
    "opentelemetry-instrumentation-requests==0.65b0",
    "opentelemetry-instrumentation-sqlite3==0.65b0",
    "opentelemetry-instrumentation-starlette==0.65b0",
    "opentelemetry-instrumentation-threading==0.65b0",
    "opentelemetry-instrumentation-tortoiseorm==0.65b0",
    "opentelemetry-instrumentation-urllib==0.65b0",
    "opentelemetry-instrumentation-urllib3==0.65b0",
    "opentelemetry-instrumentation-wsgi==0.65b0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "mypy>=2.3.1",
    "pre-commit>=4.6.2",
    "ruff>=0.11.0",
]

[tool.ruff]
exclude = ["alembic"]

[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
    "C4",  # flake8-comprehensions
    "UP",  # pyupgrade
    "ARG001", # unused arguments in functions
    "T201",   # print statements are not allowed
]
ignore = [
    "E501",  # line too long, handled by ruff-format
    "B008",  # do not perform function calls in argument defaults
    "B904",  # Allow raising exceptions without from e, for HTTPException
]

[tool.mypy]
strict = true
exclude = ["venv", ".venv", "alembic"]

[tool.fastapi]
entrypoint = "app.main:app"
