services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.158.0
    command: ["--config=/etc/otel-collector.yaml"]
    volumes:
      - ./etc/collector/collector-config-dev.yaml:/etc/otel-collector.yaml
    ports:
      - 4317:4317
      - 4318:4318
      - 55679:55679  # http://localhost:55679/debug/servicez
